# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- 
  task: ChocolateyCommand@0
  inputs:
    command: 'install'
    installPackageId: 'packer'

- 
  task: PowerShell@2
  inputs:
    filePath: 'helpers/CreateAzureVMFromPackerTemplate.ps1'

- 
  task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'GenerateResourcesAndImage -SubscriptionId db75fe6b-48a1-468c-8507-7a8fea61c1e8 -ResourceGroupName "vs2019-server2019-agent-pool" -ImageGenerationRepositoryRoot $(System.DefaultWorkingDirectory) -ImageType VS2019 -AzureLocation "East US"'