# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- 
  task: AzurePowerShell@4
  inputs:
    azureSubscription: 'Qualtrax Development Subscription'
    ScriptType: 'InlineScript'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    Inline: |
      Import-Module -Name C:\Modules\azurerm_6.7.0\AzureRM\6.7.0\AzureRM.psd1 -Global
      Get-Module -ListAvailable;
      Import-Module AzureRM.profile;
      . "$(System.DefaultWorkingDirectory)\helpers\GenerateResourcesAndImage.ps1";
      GenerateResourcesAndImage -SubscriptionId "db75fe6b-48a1-468c-8507-7a8fea61c1e8" -ResourceGroupName "vs2019-server2019-agent-pool" -ImageGenerationRepositoryRoot $(System.DefaultWorkingDirectory) -ImageType VS2019 -AzureLocation "East US"
    azurePowerShellVersion: 'LatestVersion'
    